### ISSUE TITLE
how do i reset the map?

### ISSUE THREAD

**Issue by zShayz** [Zabuzard/EldenRingInteractiveMapItemProgression#1]
i made a new save game so i need to reset the tracker but i cant find where the tracker data located, can u please tell me how?
btw awesome work, really appreciate the script

**Comment by Zabuzard** [comment]
Its in your `localStorage`. That is a system in your browser (which can also be wiped similar to cookies via the browser history menu or similar). You can also interact with it directly through the browsers console though.

1. Therefore, open your browsers debugging tools (F12)
2. Go to the "console" tab
3. To export your current content, you can type `localStorage.getItem("eldenringmap_completedItems");` and hit "execute". It is a simple string that you can just copy-paste
4. To clear it, you can enter `localStorage.removeItem("eldenringmap_completedItems");`. which will get rid of it completely.
5. To import back your old content, you can use `localStorage.setItem("eldenringmap_completedItems", "...");` where `"..."` is your old content as a simple string.

![export](https://i.imgur.com/9WISM55.png)

**Comment by zShayz** [comment]
thank u so much for the detail instruction <3
